/**
 * Write-back loops (SCOPE 3.5, ADR-0003/0004, CONTEXT.md "Write-back loop" /
 * "Demotion" / "Entity category").
 *
 * The canonical pattern for anything language-shaped: the index PROPOSES (a
 * deterministic shortlist + context), the user's LLM JUDGES, and a write-back
 * tool PERSISTS the result with model-generated provenance. The tool itself
 * ships NO intelligence (ADR-0002/0004) — the agent reading the mail is the
 * LLM. This module is the index-side ENGINE for two of the three write-back
 * instances (curation lives in `curation/`):
 *
 *  - **Summarization** ({@link saveSummary}, {@link compact}) — the agent writes
 *    a summary at message or thread level; for bulk / non-curated mail the
 *    summary REPLACES the distilled body via DEMOTION after a grace window
 *    (ADR-0003). `saveSummary` only marks eligibility; `compact` demotes.
 *  - **Domain categorization** ({@link domainsToCategorize},
 *    {@link saveDomainCategory}) — propose domains with Correspondent contacts +
 *    sample context, the LLM assigns an open-vocabulary category, persisted onto
 *    `domains.category` (CONTEXT.md "Entity category").
 *
 * Every operation is INDEX-ONLY (PLAN §4): no provider contact, no enrichment.
 * Shapes are COMPACT and token-conscious (SCOPE 3.4(b)). M3.4 wires the MCP
 * tools (`save_summary`, `save_domain_category`, `domains_to_categorize`) over
 * these; the CLI `compact` command (PLAN §13) wires {@link compact}.
 */

import type {
  CategorizeCandidateRow,
  CategorizeSample,
  Repo,
} from '../index/index.js';

/** Where a {@link saveSummary} call attaches the summary. */
export type SummaryLevel = 'message' | 'thread';

/** Result of a {@link saveSummary} write-back. */
export interface SaveSummaryResult {
  account: string;
  level: SummaryLevel;
  /** The message id or thread id the summary attached to. */
  ref: string;
  /** The `summarized_at` stamp persisted (ISO). */
  summarizedAt: string;
}

/** Options for {@link saveSummary}. */
export interface SaveSummaryOptions {
  /** Provenance: model-generated by default (ADR-0003). */
  isModel?: boolean;
  /** `summarized_at` stamp; defaults to wall clock (deterministic testing). */
  at?: string;
}

/**
 * Persist an agent-authored summary at message OR thread level (ADR-0003). The
 * summary is provenance-marked, FTS-indexed at message level (improving
 * recall), and NEVER overwrites the source fields. At message level this also
 * marks the distilled body *eligible* for demotion after the grace window — it
 * does NOT demote here (a bad summary gets retry-against-source time; the
 * demotion runs in {@link compact}). INDEX-ONLY.
 */
export async function saveSummary(
  repo: Repo,
  account: string,
  level: SummaryLevel,
  ref: string,
  text: string,
  options: SaveSummaryOptions = {},
): Promise<SaveSummaryResult> {
  const summarizedAt =
    level === 'thread'
      ? await repo.saveThreadSummary({
          account,
          threadId: ref,
          text,
          ...(options.isModel != null ? { isModel: options.isModel } : {}),
          ...(options.at != null ? { at: options.at } : {}),
        })
      : await repo.saveMessageSummary({
          account,
          gmailMessageId: ref,
          text,
          ...(options.isModel != null ? { isModel: options.isModel } : {}),
          ...(options.at != null ? { at: options.at } : {}),
        });
  return { account, level, ref, summarizedAt };
}

/** The default compaction grace window (ADR-0003): 7 days, in milliseconds. */
export const DEFAULT_GRACE_MS = 7 * 24 * 60 * 60 * 1000;

/** Options for {@link compact}. */
export interface CompactOptions {
  /**
   * Demote immediately, ignoring the grace window (`compact --now`). When set,
   * every summarized eligible body is demoted regardless of age (ADR-0003).
   */
  now?: boolean;
  /** Grace window in ms before a summarized body may demote. Defaults to 7 days. */
  graceMs?: number;
  /** The "current time" anchoring the grace cutoff (deterministic testing). */
  asOf?: Date;
  /** Cap the number of messages demoted in one pass. */
  limit?: number;
}

/** Result of a {@link compact} pass for one account. */
export interface CompactResult {
  account: string;
  /** How many eligible bodies were demoted (full → summary-only). */
  demoted: number;
  /** The grace cutoff used (ISO): rows summarized at/before this demote. */
  cutoff: string;
}

/**
 * Demote distilled bodies whose summary exists and that are bulk / non-curated,
 * older than the grace window (ADR-0003). Eligibility is fully encapsulated in
 * the repo ({@link Repo.compactEligible}): bulk only (`is_list` or
 * promotions/social), never a curated-important sender or a user-participated
 * thread. `--now` collapses the grace window to zero. INDEX-ONLY; the provider
 * remains the archive, so demotion is never data loss (Working set). Sync
 * auto-invokes this after the grace window.
 */
export async function compact(
  repo: Repo,
  account: string,
  options: CompactOptions = {},
): Promise<CompactResult> {
  const asOf = options.asOf ?? new Date();
  const graceMs = options.now ? 0 : options.graceMs ?? DEFAULT_GRACE_MS;
  const cutoff = new Date(asOf.getTime() - graceMs).toISOString();

  // Each demotion is its own atomic transaction (repo.demoteMessage). We do
  // NOT wrap the whole pass in one — node:sqlite has no nested transactions,
  // and per-message atomicity is enough: a partial compact is idempotent and
  // simply re-demotes the remainder on the next run.
  const candidates =
    options.limit != null
      ? await repo.compactEligible(account, cutoff, options.limit)
      : await repo.compactEligible(account, cutoff);
  let demoted = 0;
  for (const c of candidates) {
    if (await repo.demoteMessage(account, c.gmail_message_id)) demoted += 1;
  }
  return { account, demoted, cutoff };
}

/** A compact domain candidate the categorization loop proposes, with context. */
export interface CategorizeCandidate {
  domain: string;
  msgs: number;
  distinctContacts: number;
  correspondentCount: number;
  /** The current category, if already assigned (null when uncategorized). */
  category: string | null;
  categoryNote: string | null;
  /** Sample senders + recent subjects giving the agent context to judge. */
  samples: {
    address: string;
    displayName: string | null;
    msgsSent: number;
    msgsReceived: number;
    subjects: string[];
  }[];
}

/** Options for {@link domainsToCategorize}. */
export interface DomainsToCategorizeOptions {
  /** Include domains that already carry a category (default: uncategorized only). */
  includeCategorized?: boolean;
  /** Max candidate domains (token-conscious; default 20). */
  limit?: number;
  /** Max sample senders per domain (default 5). */
  senderLimit?: number;
  /** Max recent subjects per sample sender (default 3). */
  subjectLimit?: number;
}

function toCandidate(row: CategorizeCandidateRow, samples: CategorizeSample[]): CategorizeCandidate {
  return {
    domain: row.domain,
    msgs: row.msgs,
    distinctContacts: row.distinct_contacts,
    correspondentCount: row.correspondent_count,
    category: row.category,
    categoryNote: row.category_note,
    samples: samples.map((s) => ({
      address: s.address,
      displayName: s.display_name,
      msgsSent: s.msgs_sent,
      msgsReceived: s.msgs_received,
      subjects: s.subjects,
    })),
  };
}

/**
 * Propose domains to categorize (the PROPOSE side, PLAN §12, CONTEXT.md "Entity
 * category"). Surfaces domains with Correspondent contacts (back-and-forth
 * communication) plus sample senders/subjects as the context the agent's LLM
 * needs to assign a category. Ranked by Correspondent count then volume; default
 * to uncategorized domains. INDEX-ONLY, token-conscious (compact shapes,
 * default limits). Empty array when nothing qualifies.
 */
export async function domainsToCategorize(
  repo: Repo,
  account: string,
  options: DomainsToCategorizeOptions = {},
): Promise<CategorizeCandidate[]> {
  const rows = await repo.domainsToCategorize(account, {
    ...(options.includeCategorized != null ? { includeCategorized: options.includeCategorized } : {}),
    limit: options.limit ?? 20,
  });
  return Promise.all(
    rows.map(async (row) => {
      const samples = await repo.categorizeSamples(account, row.domain, {
        senderLimit: options.senderLimit ?? 5,
        subjectLimit: options.subjectLimit ?? 3,
      });
      return toCandidate(row, samples);
    }),
  );
}

/** Result of a {@link saveDomainCategory} write-back. */
export interface SaveDomainCategoryResult {
  account: string;
  domain: string;
  category: string;
}

/**
 * Persist an agent-assigned domain category (the PERSIST side of the
 * categorization write-back, PLAN §12, CONTEXT.md "Entity category"). The
 * category is open vocabulary (client, vendor, travel operator, finance,
 * publisher, …) — NOT a closed enum — so the agent is never boxed in. Stamps
 * `categorized_at`. Upserts the domain row (so a domain with no aggregate yet
 * can still be categorized). INDEX-ONLY. Throws on empty inputs.
 */
export async function saveDomainCategory(
  repo: Repo,
  account: string,
  domain: string,
  category: string,
  note?: string | null,
): Promise<SaveDomainCategoryResult> {
  const d = domain.trim();
  const c = category.trim();
  if (d === '') throw new Error('saveDomainCategory requires a non-empty domain');
  if (c === '') throw new Error('saveDomainCategory requires a non-empty category');
  await repo.setDomainCategory({ account, domain: d, category: c, note: note ?? null });
  return { account, domain: d, category: c };
}
